### ISSUE TITLE
When using tera treesitter highlighting on helix, html syntax highlighting stops

### ISSUE THREAD

**Issue by flashgnash** [uncenter/tree-sitter-tera#17]
I've tried setting this up on Helix, and Tera highlighting seems to work, however HTML syntax highlighting doesn't seem to work

![image](https://github.com/user-attachments/assets/5c9f3066-b31e-4586-8f11-0ecd06dabb18)

Is this a known thing or have I done something wrong in setting it up?

**Comment by uncenter** [comment]
Yeah sorry that currently doesn't work, see https://github.com/uncenter/tree-sitter-tera/issues/2. I'll try to work on that today :)

**Comment by uncenter** [comment]
Going to close in favor of #2 actually.

**Comment by flashgnash** [comment]
> Yeah sorry that currently doesn't work, see https://github.com/uncenter/tree-sitter-tera/issues/2. I'll try to work on that today :)

Is there any kind of workaround? I only need html working

**Comment by uncenter** [comment]
You can use the https://github.com/uncenter/tree-sitter-tera/tree/html-injections branch, where I just pushed a commit hardcoding the HTML injections.

**Comment by flashgnash** [comment]
> You can use the https://github.com/uncenter/tree-sitter-tera/tree/html-injections branch, where I just pushed a commit hardcoding the HTML injections.

Thank you, greatly appreciated will give it a go in a bit

**Comment by flashgnash** [comment]
Sorted, both syntaxes are highlighted now, thank you 👍
